#:schema: "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"

version: 2
final_space: true
console_title_template: "{{ .Shell }} in {{ .Folder }}"

blocks:
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: path
        style: plain
        background: transparent
        foreground: blue
        template: "{{ .Path }}"
        properties:
          style: full

  - type: rprompt
    overflow: hidden
    segments:
      - type: executiontime
        style: plain
        foreground: yellow
        background: transparent
        template: "{{ .FormattedMs }}"
        properties:
          threshold: 5000

  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        style: plain
        foreground_templates:
          - "{{if gt .Code 0}}red{{end}}"
          - "{{if eq .Code 0}}magenta{{end}}"
        background: transparent
        template: "❯"

transient_prompt:
  foreground_templates:
    - "{{if gt .Code 0}}red{{end}}"
    - "{{if eq .Code 0}}magenta{{end}}"
  background: transparent
  template: "❯ "

secondary_prompt:
  foreground: magenta
  background: transparent
  template: "❯❯ "
