import = [
"~/.config/alacritty/themes/github_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x=10
padding.y=10
dimensions.columns = 150
dimensions.lines = 40
decorations = "Buttonless"

opacity = 0.8
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 15
